### ISSUE TITLE
Indentation in lint.yml

### ISSUE THREAD

**Issue by kromesky** [kiswa/angular2-base#1]
I was having a problem when issuing the gulp command. I got the error `You need to have Ruby and scss-lint gem installed` . 

I do have Ruby and scss-lint installed, and after a bit of googling I found this issue [plugin not seeing Ruby or scss-lint gem?](https://github.com/juanfran/gulp-scss-lint/issues/11#issuecomment-56846362) which points to the issue of indentation in the lint.yml. I edited lint.yml to use 2 spaces for indentation, and this seemed to fix the problem for me.

**Comment by kiswa** [comment]
Good to know. I'll update the file!
