### ISSUE TITLE
bug in gulpfile.js

### ISSUE THREAD

**Issue by kromesky** [kiswa/angular2-base#2]
when executing a `gulp watch` and making a change to a .scss file, gulp coughed an error:

```
File angular2-base/src/scss/_core.scss was changed. Running tasks... 
[15:00:13] Task 'styles' is not in your gulpfile
```

This looks like a typo at [gulpfile.js#L106](https://github.com/kiswa/angular2-base/blob/95fcddb50296020bea4424167de4e02c52aa301e/gulpfile.js#L106) - `'styles'` should be `'scss'`.

**Comment by kiswa** [comment]
You are correct. That was changed in the update to rc.1, but missed in the `watch` task.
